//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escape
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstantiatedEntity
    {
        public int Id { get; set; }
        public int sceneID { get; set; }
        public int entityID { get; set; }
    
        public virtual Entity Entity { get; set; }
        public virtual Scene Scene { get; set; }
    }
}
